{
 "title": "COSMIC-VLA-DELAY",
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Antenna",
    "query": "ea01, ea02, ea03, ea04, ea05, ea06, ea07, ea08, ea09, ea10, ea11, ea12, ea13, ea14, ea15, ea16, ea17, ea18, ea19, ea20, ea21, ea22, ea23, ea24, ea25, ea26, ea27, ea28"
   }
  ]
 },
 "panels": [
  { "title": "Phase Centre Controller", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Right Ascension (degrees) instructed by Phase Centre Controller",
   "type": "timeseries",
   "description": "Plot of Right Ascension in degrees vs loadtime. This is the value instructed to be loaded at loadtime by the phase centre controller. ",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "targets": [
    {
     "dataset": "iox",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"delays\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"phase_centre_controller\")\n  |> filter(fn: (r) => r[\"_field\"] == \"ra_deg\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")",
     "rawSql": "SELECT\n  \"time\",\n  \"ra_deg\"\nFROM \"phase_centre_controller\"\nWHERE \"ra_deg\" IS NOT NULL\n  AND $__timeFilter(\"time\")\nORDER BY \"time\" ASC"
    }
   ]
  },
  {
   "title": "Declination (degrees) instructed by Phase Centre Controller",
   "type": "timeseries",
   "description": "Plot of Declination in degrees vs loadtime. This is the value instructed to be loaded at loadtime by the phase centre controller. ",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "targets": [
    {
     "dataset": "iox",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"delays\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"phase_centre_controller\")\n  |> filter(fn: (r) => r[\"_field\"] == \"dec_deg\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")",
     "rawSql": "SELECT\n  \"time\",\n  \"dec_deg\"\nFROM \"phase_centre_controller\"\nWHERE \"dec_deg\" IS NOT NULL\n  AND $__timeFilter(\"time\")\nORDER BY \"time\" ASC"
    }
   ]
  },
  {
   "title": "Phase Centre Controller sideband values",
   "type": "timeseries",
   "description": "The sideband values the phase centre controller is putting out for the delay model to track with.",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dataset": "iox",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"delays\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"phase_centre_controller\")\n  |> filter(fn: (r) => r[\"_field\"] == \"sideband\")\n  |> filter(fn: (r) => r[\"tune\"] == \"0\" or r[\"tune\"] == \"1\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")",
     "rawSql": "SELECT\n  \"time\",\n  \"tune\",\n  CAST(\"sideband\" AS INT) AS \"sideband\"\nFROM \"phase_centre_controller\"\nWHERE \"sideband\" IS NOT NULL\n  AND $__timeFilter(\"time\")\nORDER BY \"time\" ASC"
    }
   ]
  },
  {
   "title": "Phase Centre Controller sslo values",
   "type": "timeseries",
   "description": "The sslo values the phase centre controller is putting out for the delay model to track with.",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "rothz" } },
   "targets": [
    {
     "dataset": "iox",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"delays\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"phase_centre_controller\")\n  |> filter(fn: (r) => r[\"_field\"] == \"sslo\")\n  |> filter(fn: (r) => r[\"tune\"] == \"0\" or r[\"tune\"] == \"1\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")",
     "rawSql": "SELECT\n  \"time\",\n  \"tune\",\n  \"sslo\"\nFROM \"phase_centre_controller\"\nWHERE \"sslo\" IS NOT NULL\n  AND $__timeFilter(\"time\")\nORDER BY \"time\" ASC"
    }
   ]
  },
  { "title": "Delay Engine Tracking", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Right Ascension (degrees)",
   "type": "timeseries",
   "description": "Plot of Right Ascension in degrees vs loadtime. This is the value received by the delay model from the source finder. The current model delays set to load at loadtime are calculated for this right ascension. Note that there may be up to 5s before the F-Engines reflect these delays as that is the average loadtime.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "targets": [
    {
     "dataset": "iox",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"delays\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"delay_pointing\")\n  |> filter(fn: (r) => r[\"_field\"] == \"deg_ra\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"last\")",
     "rawSql": "SELECT\n  \"time\",\n  \"deg_ra\" AS \"right_ascension\"\nFROM \"delay_pointing\"\nWHERE \"deg_ra\" IS NOT NULL\n  AND $__timeFilter(\"time\")\nORDER BY \"time\" ASC"
    }
   ]
  },
  {
   "title": "Declination (degrees)",
   "type": "timeseries",
   "description": "The declination vs loadtime. This is the value received by the delay model from the source finder. The current model delays are calculated for this declination. Note that there may be up to 5s before the F-Engines reflect these delays as that is the average loadtime.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "targets": [
    {
     "dataset": "iox",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"delays\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"delay_pointing\")\n  |> filter(fn: (r) => r[\"_field\"] == \"deg_dec\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")",
     "rawSql": "SELECT\n  \"time\",\n  \"deg_dec\" AS \"declination\"\nFROM \"delay_pointing\"\nWHERE \"deg_dec\" IS NOT NULL\n  AND $__timeFilter(\"time\")\nORDER BY \"time\" ASC"
    }
   ]
  },
  {
   "title": "Current Antenna Calibration Values",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 }
  },
  {
   "title": "Path on disk to currently loaded delays",
   "type": "table",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 20 },
   "targets": [
    { "command": "hget", "field": "fixed_delay", "keyName": "CAL_fixedValuePaths", "type": "command" }
   ]
  },
  {
   "title": "Path on disk to currently loaded phases",
   "type": "table",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 20 },
   "targets": [
    { "command": "hget", "field": "fixed_phase", "keyName": "CAL_fixedValuePaths", "type": "command" }
   ]
  },
  { "title": "All antenna delay state", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "State of delay tracking across all antenna",
   "type": "stat",
   "description": "States are:\nGood = delay tracking thread is initialised and turned on to track.\nBad = delay tracking thread is initialised but has not been turned to track - likely means thread failed due to F-Engine timing.\nOff = delay tracking thread is not even initialised - likely means F-Engine is not configured and in operation.",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "iox",
     "query": "from(bucket: \"delays\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"delay_state\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"tracking_alive\")\r\n  |> filter(fn: (r) => r[\"ant\"] == \"ea01\" or r[\"ant\"] == \"ea02\" or r[\"ant\"] == \"ea03\" or r[\"ant\"] == \"ea04\" or r[\"ant\"] == \"ea05\" or r[\"ant\"] == \"ea06\" or r[\"ant\"] == \"ea07\" or r[\"ant\"] == \"ea08\" or r[\"ant\"] == \"ea09\" or r[\"ant\"] == \"ea10\" or r[\"ant\"] == \"ea11\" or r[\"ant\"] == \"ea12\" or r[\"ant\"] == \"ea13\" or r[\"ant\"] == \"ea14\" or r[\"ant\"] == \"ea15\" or r[\"ant\"] == \"ea16\" or r[\"ant\"] == \"ea17\" or r[\"ant\"] == \"ea18\" or r[\"ant\"] == \"ea19\" or r[\"ant\"] == \"ea20\" or r[\"ant\"] == \"ea21\" or r[\"ant\"] == \"ea22\" or r[\"ant\"] == \"ea23\" or r[\"ant\"] == \"ea24\" or r[\"ant\"] == \"ea25\" or r[\"ant\"] == \"ea26\" or r[\"ant\"] == \"ea27\" or r[\"ant\"] == \"ea28\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")",
     "rawSql": "SELECT\r\n  \"time\",\r\n  \"ant\",\r\n  CASE\r\n    WHEN \"tracking_alive\" = 0 THEN -1\r\n    WHEN \"tracking_alive\" = 1 AND \"tracking_ok\" = 0 THEN 0\r\n    WHEN \"tracking_alive\" = 1 AND \"tracking_ok\" = 1 THEN 1\r\n    ELSE -1\r\n  END AS \"status_code\"\r\nFROM \"delay_state\"\r\nWHERE \"tracking_alive\" IS NOT NULL\r\n  AND $__timeFilter(\"time\")\r\nORDER BY \"time\" ASC"
    }
   ]
  },
  {
   "title": "Total Calibration grade",
   "type": "timeseries",
   "description": "Determined by:\n|sum_frequencies(sum_antenna(gains))| / sum_frequencies(sum_antenna(|gains|))",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 38 },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT\r\n  \"time\",\r\n  \"calibration_grade\"\r\nFROM \"fix_paths\"\r\nWHERE \"calibration_grade\" IS NOT NULL\r\nORDER BY \"time\" DESC\r\nLIMIT 5"
    }
   ]
  },
  { "title": "Antenna $Antenna Delay State", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 } },
  {
   "title": "${Antenna} F-shift status",
   "type": "stat",
   "description": "An aggregate for all F-Engine streams of whether the F-Shift applied matches that which is broadcast from mcast. This being Bad is not necessarily indicative of anything broken, as if the system is not recording, it will not load the currently broadcast fshifts to the F-Engines.",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 50 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "iox",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"delays\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"delay_state\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"fshifts_correct\")\r\n  |> filter(fn: (r) => r[\"ant\"] == \"${Antenna}\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")",
     "rawSql": "SELECT\r\n  \"time\",\r\n  \"fshifts_correct\" AS \"status\"\r\nFROM \"delay_state\"\r\nWHERE \"ant\" = '${Antenna}'\r\n  AND \"fshifts_correct\" IS NOT NULL\r\n  AND $__timeFilter(\"time\")\r\nORDER BY \"time\" DESC\r\nLIMIT 1"
    }
   ]
  },
  {
   "title": "${Antenna} Phase status",
   "type": "stat",
   "description": "An aggregate for all F-Engine streams of whether the Phases applied are correct for the current sample time. This is calculated by reading phases off of the F-Engine sometime after loading and checking that they match the expected interpolated value These are the phases derived from the applied delay during tracking.",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 50 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "iox",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"delays\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"delay_state\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"phase_correct\")\r\n  |> filter(fn: (r) => r[\"ant\"] == \"${Antenna}\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")",
     "rawSql": "SELECT\r\n  \"time\",\r\n  \"phase_correct\" AS \"status\"\r\nFROM \"delay_state\"\r\nWHERE \"ant\" = '${Antenna}'\r\n  AND \"phase_correct\" IS NOT NULL\r\n  AND $__timeFilter(\"time\")\r\nORDER BY \"time\" DESC\r\nLIMIT 1"
    }
   ]
  },
  {
   "title": "${Antenna} Loadtime status",
   "type": "stat",
   "description": "Whether delays are loaded at the loadtime specified by the delay model. This is tested by checking the time_since_loaded value for the delays on the F-Engines corresponds to loadtime instructed.",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 50 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "iox",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"delays\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"delay_state\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"loadtime_accurate\")\r\n  |> filter(fn: (r) => r[\"ant\"] == \"${Antenna}\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")",
     "rawSql": "SELECT\r\n  \"time\",\r\n  \"loadtime_accurate\" AS \"status\"\r\nFROM \"delay_state\"\r\nWHERE \"ant\" = '${Antenna}'\r\n  AND \"loadtime_accurate\" IS NOT NULL\r\n  AND $__timeFilter(\"time\")\r\nORDER BY \"time\" DESC\r\nLIMIT 1"
    }
   ]
  },
  {
   "title": "${Antenna} Phase Calibration Values Loaded status",
   "type": "stat",
   "description": "Whether the phase calibration values calculated during the calibration run that are expected to have been loaded are loaded. This is checked in every calibration run, half a second after instructing the delay tracking thread to load the calibration delays.",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 50 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "iox",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"delays\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"delay_state\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"phase_cal_correct\")\r\n  |> filter(fn: (r) => r[\"ant\"] == \"${Antenna}\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")",
     "rawSql": "SELECT\r\n  \"time\",\r\n  \"phase_cal_correct\" AS \"status\"\r\nFROM \"delay_state\"\r\nWHERE \"ant\" = '${Antenna}'\r\n  AND \"phase_cal_correct\" IS NOT NULL\r\n  AND $__timeFilter(\"time\")\r\nORDER BY \"time\" DESC\r\nLIMIT 1"
    }
   ]
  },
  {
   "title": "${Antenna} loading correct delays",
   "type": "stat",
   "description": "An aggregate for all F-Engine streams of whether the Delays applied are correct for the current sample time. This is calculated by reading delays off of the F-Engine sometime after loading and checking that they match the expected interpolated value. The delays are the sum of the calibration fixed delays and geometric.",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 50 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "iox",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"delays\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"delay_state\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"delay_correct\")\r\n  |> filter(fn: (r) => r[\"ant\"] == \"${Antenna}\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")",
     "rawSql": "SELECT\r\n  \"time\",\r\n  \"delay_correct\" AS \"status\"\r\nFROM \"delay_state\"\r\nWHERE \"ant\" = '${Antenna}'\r\n  AND \"delay_correct\" IS NOT NULL\r\n  AND $__timeFilter(\"time\")\r\nORDER BY \"time\" DESC\r\nLIMIT 1"
    }
   ]
  },
  {
   "title": "${Antenna} Sideband status",
   "type": "stat",
   "description": "An aggregate for all F-Engine tunings of whether the sideband being used for phase calculations on the F-Engine matches that received from the delay model for that sample time.",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 50 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "iox",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"delays\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"tune_values\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"current_sideband\")\r\n  |> filter(fn: (r) => r[\"ant\"] == \"${Antenna}\")\r\n  |> filter(fn: (r) => r[\"tune\"] == \"0\" or r[\"tune\"] == \"1\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")",
     "rawSql": "SELECT\r\n  MIN(CASE WHEN t.\"current_sideband\" = c.\"sideband\" THEN 1 ELSE 0 END) AS \"status\"\r\nFROM\r\n  (\r\n    SELECT \"tune\", \"current_sideband\"\r\n    FROM (\r\n      SELECT \"tune\", \"current_sideband\",\r\n             ROW_NUMBER() OVER(PARTITION BY \"tune\" ORDER BY \"time\" DESC) as rn\r\n      FROM \"tune_values\"\r\n      WHERE \"ant\" = '${Antenna}' \r\n        AND \"current_sideband\" IS NOT NULL\r\n        AND $__timeFilter(\"time\")\r\n    )\r\n    WHERE rn = 1\r\n  ) t\r\nJOIN\r\n  (\r\n    SELECT \"tune\", \"sideband\"\r\n    FROM (\r\n      SELECT \"tune\", \"sideband\",\r\n             ROW_NUMBER() OVER(PARTITION BY \"tune\" ORDER BY \"time\" DESC) as rn\r\n      FROM \"phase_centre_controller\"\r\n      WHERE \"sideband\" IS NOT NULL\r\n        AND $__timeFilter(\"time\")\r\n    )\r\n    WHERE rn = 1\r\n  ) c\r\nON t.\"tune\" = c.\"tune\""
    }
   ]
  },
  {
   "title": "${Antenna} Tracking Mode",
   "type": "table",
   "description": "The tracking mode for the antenna.",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 54 },
   "targets": [
    {
     "dataset": "iox",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"delays\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"delay_state\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"tracking_mode\")\r\n  |> filter(fn: (r) => r[\"ant\"] == \"${Antenna}\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")",
     "rawSql": "SELECT\r\n  \"time\",\r\n  \"tracking_mode\"\r\nFROM \"delay_state\"\r\nWHERE \"ant\" = '${Antenna}'\r\n  AND \"tracking_mode\" IS NOT NULL\r\n  AND $__timeFilter(\"time\")\r\nORDER BY \"time\" DESC\r\nLIMIT 1"
    }
   ]
  },
  {
   "title": "${Antenna} Tracking Alive",
   "type": "stat",
   "description": "This panel dictates if the tracking thread is even alive for this antenna which if False, indicates that the antenna may be out of commission.",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 54 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "iox",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"delays\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"delay_state\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"tracking_alive\")\r\n  |> filter(fn: (r) => r[\"ant\"] == \"${Antenna}\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")",
     "rawSql": "SELECT\r\n  \"time\",\r\n  \"tracking_alive\" AS \"status\"\r\nFROM \"delay_state\"\r\nWHERE \"ant\" = '${Antenna}'\r\n  AND \"tracking_alive\" IS NOT NULL\r\n  AND $__timeFilter(\"time\")\r\nORDER BY \"time\" DESC\r\nLIMIT 1"
    }
   ]
  },
  {
   "title": "${Antenna} Tracking status",
   "type": "stat",
   "description": "The state of the tracking status. If good, this means that tracking has been switched on for the antenna - the mode of which is visible in the tracking mode panel.",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 54 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "iox",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"delays\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"delay_state\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"tracking_ok\")\r\n  |> filter(fn: (r) => r[\"ant\"] == \"${Antenna}\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")",
     "rawSql": "SELECT\r\n  \"time\",\r\n  \"tracking_ok\" AS \"status\"\r\nFROM \"delay_state\"\r\nWHERE \"ant\" = '${Antenna}'\r\n  AND \"tracking_ok\" IS NOT NULL\r\n  AND $__timeFilter(\"time\")\r\nORDER BY \"time\" DESC\r\nLIMIT 1"
    }
   ]
  },
  {
   "title": "F-Shifts loaded for ${Antenna} stream 0",
   "type": "stat",
   "description": "The F-Shift value loaded at present on the antenna for stream 0. Check the F-Shifts correct panel for information about whether this matches what is broadcast on mcast.",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "rothz" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "iox",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"delays\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"delay_values\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"loaded_fshift_hz\")\r\n  |> filter(fn: (r) => r[\"ant\"] == \"${Antenna}\")\r\n  |> filter(fn: (r) => r[\"stream\"] == \"0\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"last\")",
     "rawSql": "SELECT\r\n  \"time\",\r\n  \"loaded_fshift_hz\"\r\nFROM \"delay_values\"\r\nWHERE \"ant\" = '${Antenna}'\r\n  AND \"stream\" = '0'\r\n  AND \"loaded_fshift_hz\" IS NOT NULL\r\n  AND $__timeFilter(\"time\")\r\nORDER BY \"time\" DESC\r\nLIMIT 1"
    }
   ]
  },
  {
   "title": "F-Shifts loaded for ${Antenna} stream 1",
   "type": "stat",
   "description": "The F-Shift value loaded at present for the antenna on stream 1. Check the F-Shifts correct panel for information about whether this matches what is broadcast on mcast.",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "rothz" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "iox",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"delays\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"delay_values\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"loaded_fshift_hz\")\r\n  |> filter(fn: (r) => r[\"ant\"] == \"${Antenna}\")\r\n  |> filter(fn: (r) => r[\"stream\"] == \"1\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"last\")",
     "rawSql": "SELECT\r\n  \"time\",\r\n  \"loaded_fshift_hz\"\r\nFROM \"delay_values\"\r\nWHERE \"ant\" = '${Antenna}'\r\n  AND \"stream\" = '1'\r\n  AND \"loaded_fshift_hz\" IS NOT NULL\r\n  AND $__timeFilter(\"time\")\r\nORDER BY \"time\" DESC\r\nLIMIT 1"
    }
   ]
  },
  {
   "title": "F-Shifts loaded for ${Antenna} stream 2",
   "type": "stat",
   "description": "The F-Shift value loaded at present for the antenna on stream 2. Check the F-Shifts correct panel for information about whether this matches what is broadcast on mcast.",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "rothz" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "iox",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"delays\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"delay_values\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"loaded_fshift_hz\")\r\n  |> filter(fn: (r) => r[\"ant\"] == \"${Antenna}\")\r\n  |> filter(fn: (r) => r[\"stream\"] == \"2\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"last\")",
     "rawSql": "SELECT\r\n  \"time\",\r\n  \"loaded_fshift_hz\"\r\nFROM \"delay_values\"\r\nWHERE \"ant\" = '${Antenna}'\r\n  AND \"stream\" = '2'\r\n  AND \"loaded_fshift_hz\" IS NOT NULL\r\n  AND $__timeFilter(\"time\")\r\nORDER BY \"time\" DESC\r\nLIMIT 1"
    }
   ]
  },
  {
   "title": "F-Shifts loaded for ${Antenna} stream 3",
   "type": "stat",
   "description": "The F-Shift value loaded at present for the antenna for stream 3. Check the F-Shifts correct panel for information about whether this matches what is broadcast on mcast.",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "rothz" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "iox",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"delays\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"delay_values\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"loaded_fshift_hz\")\r\n  |> filter(fn: (r) => r[\"ant\"] == \"${Antenna}\")\r\n  |> filter(fn: (r) => r[\"stream\"] == \"3\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"last\")",
     "rawSql": "SELECT\r\n  \"time\",\r\n  \"loaded_fshift_hz\"\r\nFROM \"delay_values\"\r\nWHERE \"ant\" = '${Antenna}'\r\n  AND \"stream\" = '3'\r\n  AND \"loaded_fshift_hz\" IS NOT NULL\r\n  AND $__timeFilter(\"time\")\r\nORDER BY \"time\" DESC\r\nLIMIT 1"
    }
   ]
  },
  {
   "title": "Delays applied on ${Antenna}",
   "type": "timeseries",
   "description": "Expected and firmware delays across all F-Engine streams for the antenna. \nFirmware delays are calculated by reading fractional and coarse delays off of the F-Engines.\nExpected delays are calculated by knowing what calibration delay and geometric delay coefficients were loaded, interpolating the geometric delays to a the time of reading from the F-Engine and comparing.\nThis is the cumulative delays i.e. Calibration delays + geometric delays.",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "dataset": "iox",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"delays\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"delay_values\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"firmware_delay_ns\")\r\n  |> filter(fn: (r) => r[\"ant\"] == \"${Antenna}\")\r\n  |> filter(fn: (r) => r[\"stream\"] == \"0\" or r[\"stream\"] == \"1\" or r[\"stream\"] == \"2\" or r[\"stream\"] == \"3\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"last\")",
     "rawSql": "SELECT\n  \"time\",\n  \"stream\",\n  \"expected_delay_ns\",\n  \"firmware_delay_ns\"\nFROM \"delay_values\"\nWHERE \"ant\" = '${Antenna}'\n  AND \"expected_delay_ns\" IS NOT NULL\n  AND \"firmware_delay_ns\" IS NOT NULL\n  AND $__timeFilter(\"time\")\nORDER BY \"time\" ASC"
    }
   ]
  },
  {
   "title": "Calibration delays to be applied to ${Antenna}",
   "type": "timeseries",
   "description": "The calibration delays produced via the calibration process and sent out to be loaded to F-Engines within half a second. Note that these values will differ from those in the .csv file as they are offset by (8e3/(0.66 * c))*1e9 ns.",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "dataset": "iox",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"delays\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"fix_delays\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"fixed_delay_ns\")\r\n  |> filter(fn: (r) => r[\"ant\"] == \"${Antenna}\")\r\n  |> filter(fn: (r) => r[\"stream\"] == \"0\" or r[\"stream\"] == \"1\" or r[\"stream\"] == \"2\" or r[\"stream\"] == \"3\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")",
     "rawSql": "SELECT\n  \"time\",\n  \"stream\",\n  \"fixed_delay_ns\"\nFROM \"fix_delays\"\nWHERE \"ant\" = '${Antenna}'\n  AND \"fixed_delay_ns\" IS NOT NULL\n  AND $__timeFilter(\"time\")\nORDER BY \"time\" ASC"
    }
   ]
  },
  {
   "title": "First order Geometric delays to be applied to ${Antenna}",
   "type": "timeseries",
   "description": "The calculated geometric delay (1st order coefficient) produced via the delaymodel process and sent out to be loaded to F-Engines at loadtime.",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "dataset": "iox",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"delays\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"delay_coeff\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"delay_ns\")\r\n  |> filter(fn: (r) => r[\"ant\"] == \"${Antenna}\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")",
     "rawSql": "SELECT\n  \"time\",\n  \"delay_ns\" AS \"geometric_delay_ns\"\nFROM \"delay_coeff\"\nWHERE \"ant\" = '${Antenna}'\n  AND \"delay_ns\" IS NOT NULL\n  AND $__timeFilter(\"time\")\nORDER BY \"time\" ASC"
    }
   ]
  },
  {
   "title": "Second order Geometric delays to be applied to ${Antenna}",
   "type": "timeseries",
   "description": "The calculated geometric delay (2nd order coefficient) produced via the delaymodel process and sent out to be loaded to F-Engines at loadtime.",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 94 },
   "fieldConfig": { "defaults": { "unit": "ns/s" } },
   "targets": [
    {
     "dataset": "iox",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"delays\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"delay_coeff\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"delay_rate_nsps\")\r\n  |> filter(fn: (r) => r[\"ant\"] == \"${Antenna}\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")",
     "rawSql": "SELECT\n  \"time\",\n  \"delay_rate_nsps\"\nFROM \"delay_coeff\"\nWHERE \"ant\" = '${Antenna}'\n  AND \"delay_rate_nsps\" IS NOT NULL\n  AND $__timeFilter(\"time\")\nORDER BY \"time\" ASC"
    }
   ]
  },
  {
   "title": "Third order Geometric delays to be applied to ${Antenna}",
   "type": "timeseries",
   "description": "The calculated geometric delay (3rd order coefficient) produced via the delaymodel process and sent out to be loaded to F-Engines at loadtime.",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 105 },
   "fieldConfig": { "defaults": { "unit": "ns/s" } },
   "targets": [
    {
     "dataset": "iox",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"delays\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"delay_coeff\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"delay_raterate_nsps2\")\r\n  |> filter(fn: (r) => r[\"ant\"] == \"${Antenna}\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")",
     "rawSql": "SELECT\n  \"time\",\n  \"delay_raterate_nsps2\"\nFROM \"delay_coeff\"\nWHERE \"ant\" = '${Antenna}'\n  AND \"delay_raterate_nsps2\" IS NOT NULL\n  AND $__timeFilter(\"time\")\nORDER BY \"time\" ASC"
    }
   ]
  },
  {
   "title": "Phases applied to ${Antenna}",
   "type": "timeseries",
   "description": "Expected and firmware phases across all F-Engine streams for the antenna. \nFirmware phases are calculated by reading loaded phases off of the F-Engines.\nExpected phases are calculated by knowing what phases and rates were loaded, interpolating the geometric delays to a the time of reading from the F-Engine and comparing.",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 116 },
   "fieldConfig": { "defaults": { "unit": "radian" } },
   "targets": [
    {
     "dataset": "iox",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"delays\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"delay_values\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"expected_phase_rad\")\r\n  |> filter(fn: (r) => r[\"ant\"] == \"${Antenna}\")\r\n  |> filter(fn: (r) => r[\"stream\"] == \"0\" or r[\"stream\"] == \"1\" or r[\"stream\"] == \"2\" or r[\"stream\"] == \"3\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"last\")",
     "rawSql": "SELECT\n  \"time\",\n  \"stream\",\n  \"expected_phase_rad\",\n  \"firmware_phase_rad\"\nFROM \"delay_values\"\nWHERE \"ant\" = '${Antenna}'\n  AND \"expected_phase_rad\" IS NOT NULL\n  AND \"firmware_phase_rad\" IS NOT NULL\n  AND $__timeFilter(\"time\")\nORDER BY \"time\" ASC"
    }
   ]
  }
 ]
}