{
 "title": "COSMIC-VLA-SYSTEMD",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Unit State Count",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(node_systemd_unit_state) by (state)",
     "legendFormat": "{{ state }}"
    }
   ]
  },
  {
   "title": "Geometric Delay Model Service",
   "type": "graph",
   "description": "Delay model service state. Zone 3 is \"active\", zone 2 is \"inactive\", zone 1 is \"failed\".",
   "gridPos": { "h": 17, "w": 6, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short", "label": "service state" }
   ],
   "targets": [
    {
     "aggregation": "Last",
     "crit": 1,
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "expr": "3*sum(systemd_unit_state{name=\"delaymodel.service\", state=\"active\"}) + 2*sum(systemd_unit_state{name=\"delaymodel.service\", state=\"inactive\"}) + sum(systemd_unit_state{name=\"delaymodel.service\", state=\"failed\"})",
     "legendFormat": "delay model service",
     "units": "none",
     "valueHandler": "Number Threshold",
     "warn": 2
    }
   ]
  },
  {
   "title": "Calibration Service",
   "type": "graph",
   "description": "Calibrations service state. Zone 3 is \"active\", zone 2 is \"inactive\", zone 1 is \"failed\".",
   "gridPos": { "h": 17, "w": 6, "x": 6, "y": 11 },
   "yaxes": [
    { "format": "short", "label": "service state" }
   ],
   "targets": [
    {
     "aggregation": "Last",
     "crit": 1,
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "expr": "3*sum(systemd_unit_state{name=\"calibration_gain_collator.service\", state=\"active\"}) + 2*sum(systemd_unit_state{name=\"calibration_gain_collator.service\", state=\"inactive\"}) + sum(systemd_unit_state{name=\"calibration_gain_collator.service\", state=\"failed\"})",
     "legendFormat": "calibration service",
     "units": "none",
     "valueHandler": "Number Threshold",
     "warn": 2
    }
   ]
  },
  {
   "title": "Mcast to Redis Service",
   "type": "graph",
   "description": "Mcast to Redis service state. Zone 3 is \"active\", zone 2 is \"inactive\", zone 1 is \"failed\".",
   "gridPos": { "h": 17, "w": 6, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "short", "label": "service state" }
   ],
   "targets": [
    {
     "aggregation": "Last",
     "crit": 1,
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "expr": "3*sum(systemd_unit_state{name=\"mcast2redis.service\", state=\"active\"}) + 2*sum(systemd_unit_state{name=\"mcast2redis.service\", state=\"inactive\"}) + sum(systemd_unit_state{name=\"mcast2redis.service\", state=\"failed\"})",
     "legendFormat": "mcast2redis service",
     "units": "none",
     "valueHandler": "Number Threshold",
     "warn": 2
    }
   ]
  },
  {
   "title": "Flagged Antenna Service",
   "type": "graph",
   "description": "Flagged antenna service state. Zone 3 is \"active\", zone 2 is \"inactive\", zone 1 is \"failed\".",
   "gridPos": { "h": 17, "w": 6, "x": 18, "y": 11 },
   "yaxes": [
    { "format": "short", "label": "service state" }
   ],
   "targets": [
    {
     "aggregation": "Last",
     "crit": 1,
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "expr": "3*sum(systemd_unit_state{name=\"flaggedantenna.service\", state=\"active\"}) + 2*sum(systemd_unit_state{name=\"flaggedantenna.service\", state=\"inactive\"}) + sum(systemd_unit_state{name=\"flaggedantenna.service\", state=\"failed\"})",
     "legendFormat": "flagged antenna service",
     "units": "none",
     "valueHandler": "Number Threshold",
     "warn": 2
    }
   ]
  },
  {
   "title": "Hashpipe Meta Marshall Service",
   "type": "graph",
   "description": "Hashpipe metamarshall service state. Zone 3 is \"active\", zone 2 is \"inactive\", zone 1 is \"failed\".",
   "gridPos": { "h": 17, "w": 6, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short", "label": "service state" }
   ],
   "targets": [
    {
     "aggregation": "Last",
     "crit": 1,
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "expr": "3*sum(systemd_unit_state{name=\"hashpipe_meta_marshall.service\", state=\"active\"}) + 2*sum(systemd_unit_state{name=\"hashpipe_meta_marshall.service\", state=\"inactive\"}) + sum(systemd_unit_state{name=\"hashpipe_meta_marshall.service\", state=\"failed\"})",
     "legendFormat": "hashpipe metamarshall service",
     "units": "none",
     "valueHandler": "Number Threshold",
     "warn": 2
    }
   ]
  },
  {
   "title": "Delay Logger Service",
   "type": "graph",
   "description": "Delay logger service state. Zone 3 is \"active\", zone 2 is \"inactive\", zone 1 is \"failed\".",
   "gridPos": { "h": 17, "w": 6, "x": 6, "y": 28 },
   "yaxes": [
    { "format": "short", "label": "service state" }
   ],
   "targets": [
    {
     "aggregation": "Last",
     "crit": 1,
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "expr": "3*sum(systemd_unit_state{name=\"delaylogger.service\", state=\"active\"}) + 2*sum(systemd_unit_state{name=\"delaylogger.service\", state=\"inactive\"}) + sum(systemd_unit_state{name=\"delaylogger.service\", state=\"failed\"})",
     "legendFormat": "delay logger service",
     "units": "none",
     "valueHandler": "Number Threshold",
     "warn": 2
    }
   ]
  },
  {
   "title": "Phase Centre Controller Service",
   "type": "graph",
   "description": "Phase Centre Controller state. Zone 3 is \"active\", zone 2 is \"inactive\", zone 1 is \"failed\".",
   "gridPos": { "h": 17, "w": 6, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "short", "label": "service state" }
   ],
   "targets": [
    {
     "aggregation": "Last",
     "crit": 1,
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "expr": "3*sum(systemd_unit_state{name=\"phase_center_controller.service\", state=\"active\"}) + 2*sum(systemd_unit_state{name=\"phase_center_controller.service\", state=\"inactive\"}) + sum(systemd_unit_state{name=\"phase_center_controller.service\", state=\"failed\"})",
     "legendFormat": "phase centre controller service",
     "units": "none",
     "valueHandler": "Number Threshold",
     "warn": 2
    }
   ]
  },
  {
   "title": "Calibration logger Service",
   "type": "graph",
   "description": "Calibration logger state. Zone 3 is \"active\", zone 2 is \"inactive\", zone 1 is \"failed\".",
   "gridPos": { "h": 17, "w": 6, "x": 18, "y": 28 },
   "yaxes": [
    { "format": "short", "label": "service state" }
   ],
   "targets": [
    {
     "aggregation": "Last",
     "crit": 1,
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "expr": "3*sum(systemd_unit_state{name=\"calibrationlogger.service\", state=\"active\"}) + 2*sum(systemd_unit_state{name=\"calibrationlogger.service\", state=\"inactive\"}) + sum(systemd_unit_state{name=\"calibrationlogger.service\", state=\"failed\"})",
     "legendFormat": "phase centre controller service",
     "units": "none",
     "valueHandler": "Number Threshold",
     "warn": 2
    }
   ]
  }
 ]
}