{
 "title": "COSMIC-VLA-COMPUTE",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Node CPU Utilisation per minute over last hour",
   "type": "graph",
   "description": "Percentage utilization of CPU's per node averaged over 1min",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(1 - avg(irate(node_cpu_seconds_total{mode=\"idle\"}[1m])) by (instance)) * 100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Memory Usage per node per minute over last hour",
   "type": "graph",
   "description": "Average memory usage over 1m per node as percentage",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 * (1 - ((avg_over_time(node_memory_MemFree_bytes[1m]) + avg_over_time(node_memory_Cached_bytes[1m]) + avg_over_time(node_memory_Buffers_bytes[1m])) / avg_over_time(node_memory_MemTotal_bytes[1m])))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Total disk read bytes per instance per 30s over last hour",
   "type": "graph",
   "description": "The total disk read bytes rate per instance over 30s.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "avg by (instance) (node_disk_read_bytes_rate)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Total disk write bytes per instance per 30s over last hour",
   "type": "graph",
   "description": "The total disk write bytes rate averaged over instance per 30s",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "avg by (instance) (node_disk_written_bytes_rate)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Node temperature per instance over last hour",
   "type": "graph",
   "description": "Node temperature from sensor \"temp1\" averaged across all instances in Celsius",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "avg by (instance) (node_hwmon_temp_celsius{sensor=\"temp1\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Total received bytes per instance per 30s over last hour",
   "type": "graph",
   "description": "The total received network bytes rate averaged per instance over 30s.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "avg by (instance) (node_network_receive_bytes_rate)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Total transmit bytes per instance per 30s over last hour",
   "type": "graph",
   "description": "The total network transmit bytes rate averaged per instance over 30s.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "yaxes": [
    { "format": "binBps" }
   ],
   "targets": [
    {
     "expr": " avg by (instance) (node_network_transmit_bytes_rate)",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}