{
 "title": "COSMIC-VLA-ANTENNA",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Antenna",
    "query": "ea01, ea02, ea03, ea04, ea05, ea06, ea07, ea08, ea09, ea10, ea11, ea12, ea13, ea14, ea15, ea16, ea17, ea18, ea19, ea20, ea21, ea22, ea23, ea24, ea25, ea26, ea27, ea28"
   }
  ]
 },
 "panels": [
  {
   "title": "Antenna Pad location",
   "type": "table",
   "description": "On which VLA pad the specified antenna sits.\nPolled every 60s.",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT\r\n  \"time\",\r\n  \"ant_pad\"\r\nFROM \"feng_stat\"\r\nWHERE \"ant\" = '${Antenna}'\r\n  AND \"ant_pad\" IS NOT NULL\r\n  AND $__timeFilter(\"time\")\r\nORDER BY \"time\" DESC\r\nLIMIT 1"
    }
   ]
  },
  {
   "title": "${Antenna} delay block time",
   "type": "stat",
   "description": "The current FPGA time that the F-Engines delay is using",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsLocal" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "iox",
     "query": "from(bucket: \"fengine\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"feng_stat\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"feng_delay_time\")\r\n  |> filter(fn: (r) => r[\"ant\"] == \"${Antenna}\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")",
     "rawSql": "SELECT\r\n  \"time\",\r\n  \"feng_delay_time\"\r\nFROM \"feng_stat\"\r\nWHERE \"ant\" = '${Antenna}'\r\n  AND \"feng_delay_time\" IS NOT NULL\r\n  AND $__timeFilter(\"time\")\r\nORDER BY \"time\" DESC\r\nLIMIT 1"
    }
   ]
  },
  {
   "title": "${Antenna} lo block time",
   "type": "stat",
   "description": "The current FPGA time that the F-Engines lo is using",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsLocal" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "iox",
     "query": "from(bucket: \"fengine\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"feng_stat\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"feng_lo_time\")\r\n  |> filter(fn: (r) => r[\"ant\"] == \"${Antenna}\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")",
     "rawSql": "SELECT\r\n  \"time\",\r\n  \"feng_lo_time\"\r\nFROM \"feng_stat\"\r\nWHERE \"ant\" = '${Antenna}'\r\n  AND \"feng_lo_time\" IS NOT NULL\r\n  AND $__timeFilter(\"time\")\r\nORDER BY \"time\" DESC\r\nLIMIT 1"
    }
   ]
  },
  {
   "title": "${Antenna} phaserotate block time",
   "type": "stat",
   "description": "The current FPGA time that the F-Engines phaserotate is using",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsLocal" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "iox",
     "query": "from(bucket: \"fengine\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"feng_stat\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"feng_phaserotate_time\")\r\n  |> filter(fn: (r) => r[\"ant\"] == \"${Antenna}\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")",
     "rawSql": "SELECT\r\n  \"time\",\r\n  \"feng_phaserotate_time\"\r\nFROM \"feng_stat\"\r\nWHERE \"ant\" = '${Antenna}'\r\n  AND \"feng_phaserotate_time\" IS NOT NULL\r\n  AND $__timeFilter(\"time\")\r\nORDER BY \"time\" DESC\r\nLIMIT 1"
    }
   ]
  },
  {
   "title": "${Antenna} correct to within 1s",
   "type": "stat",
   "description": "A boolean checks that will print match if lo, delay and phaserotate times match to within 0.1s and overall match current unix time to within 1s.",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "iox",
     "query": "from(bucket: \"fengine\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"feng_stat\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"feng_time_correct\")\r\n  |> filter(fn: (r) => r[\"ant\"] == \"${Antenna}\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")",
     "rawSql": "SELECT\r\n  \"time\",\r\n  \"feng_time_correct\"\r\nFROM \"feng_stat\"\r\nWHERE \"ant\" = '${Antenna}'\r\n  AND \"feng_time_correct\" IS NOT NULL\r\n  AND $__timeFilter(\"time\")\r\nORDER BY \"time\" DESC\r\nLIMIT 1"
    }
   ]
  },
  {
   "title": "Antenna to Fengine device map",
   "type": "table",
   "description": "Mapping of Antenna name to <server>:<pcie_id>_<pipeline_id>\nUpdated every 60s",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {
     "dataset": "iox",
     "query": "from(bucket: \"fengine\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ant_stat\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"path\")\r\n  |> filter(fn: (r) => r[\"ant\"] == \"${Antenna}\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")",
     "rawSql": "SELECT\r\n  \"time\",\r\n  \"path\" AS \"ant_path\" \r\nFROM \"ant_stat\"\r\nWHERE \"ant\" = '${Antenna}'\r\n  AND \"path\" IS NOT NULL\r\n  AND $__timeFilter(\"time\")\r\nORDER BY \"time\" DESC\r\nLIMIT 1"
    }
   ]
  },
  {
   "title": "All antenna PFB overflow count",
   "type": "timeseries",
   "description": "The PFB overflow count for all antenna.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "dataset": "iox",
     "query": "from(bucket: \"fengine\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"feng_stat\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"feng_pfb_overflow_count\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")",
     "rawSql": "SELECT\r\n  \"time\",\r\n  \"ant\",\r\n  \"feng_pfb_overflow_count\"\r\nFROM \"feng_stat\"\r\nWHERE \"feng_pfb_overflow_count\" IS NOT NULL\r\n  AND $__timeFilter(\"time\")\r\nORDER BY \"time\" ASC"
    }
   ]
  },
  {
   "title": "Displacement of all Antenna from array centre",
   "type": "barchart",
   "description": "Displacement of all antenna from array centre in metres",
   "gridPos": { "h": 19, "w": 24, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "lengthm" } },
   "targets": [
    {
     "dataset": "iox",
     "query": "from(bucket: \"fengine\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ant_stat\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"displacement\")\r\n  |> filter(fn: (r) => r[\"ant\"] == \"ea01\" or r[\"ant\"] == \"ea05\" or r[\"ant\"] == \"ea02\" or r[\"ant\"] == \"ea03\" or r[\"ant\"] == \"ea04\" or r[\"ant\"] == \"ea06\" or r[\"ant\"] == \"ea07\" or r[\"ant\"] == \"ea08\" or r[\"ant\"] == \"ea09\" or r[\"ant\"] == \"ea10\" or r[\"ant\"] == \"ea11\" or r[\"ant\"] == \"ea12\" or r[\"ant\"] == \"ea13\" or r[\"ant\"] == \"ea14\" or r[\"ant\"] == \"ea15\" or r[\"ant\"] == \"ea16\" or r[\"ant\"] == \"ea17\" or r[\"ant\"] == \"ea18\" or r[\"ant\"] == \"ea19\" or r[\"ant\"] == \"ea20\" or r[\"ant\"] == \"ea21\" or r[\"ant\"] == \"ea22\" or r[\"ant\"] == \"ea24\" or r[\"ant\"] == \"ea23\" or r[\"ant\"] == \"ea25\" or r[\"ant\"] == \"ea27\" or r[\"ant\"] == \"ea26\" or r[\"ant\"] == \"ea28\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")",
     "rawSql": "SELECT\r\n  \"ant\",\r\n  \"displacement\"\r\nFROM (\r\n  SELECT\r\n    \"ant\",\r\n    \"displacement\",\r\n    ROW_NUMBER() OVER (PARTITION BY \"ant\" ORDER BY \"time\" DESC) AS rn\r\n  FROM \"ant_stat\"\r\n  WHERE \"displacement\" IS NOT NULL\r\n    AND $__timeFilter(\"time\")\r\n)\r\nWHERE rn = 1\r\nORDER BY \"ant\" ASC\r\n"
    }
   ]
  },
  { "title": "F-Engine DTS state", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "All antenna dts ok",
   "type": "stat",
   "description": "The dts ok field for all antenna.\nComputed from:\nfeng.dts.get_status_dict()['ok']\nPolled every 60s",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "iox",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"fengine\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"feng_stat\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"dts_state_ok\")\r\n  |> filter(fn: (r) => r[\"ant\"] == \"ea01\" or r[\"ant\"] == \"ea02\" or r[\"ant\"] == \"ea03\" or r[\"ant\"] == \"ea04\" or r[\"ant\"] == \"ea05\" or r[\"ant\"] == \"ea06\" or r[\"ant\"] == \"ea07\" or r[\"ant\"] == \"ea08\" or r[\"ant\"] == \"ea09\" or r[\"ant\"] == \"ea10\" or r[\"ant\"] == \"ea11\" or r[\"ant\"] == \"ea12\" or r[\"ant\"] == \"ea13\" or r[\"ant\"] == \"ea14\" or r[\"ant\"] == \"ea15\" or r[\"ant\"] == \"ea17\" or r[\"ant\"] == \"ea16\" or r[\"ant\"] == \"ea18\" or r[\"ant\"] == \"ea19\" or r[\"ant\"] == \"ea20\" or r[\"ant\"] == \"ea21\" or r[\"ant\"] == \"ea22\" or r[\"ant\"] == \"ea23\" or r[\"ant\"] == \"ea24\" or r[\"ant\"] == \"ea25\" or r[\"ant\"] == \"ea26\" or r[\"ant\"] == \"ea27\" or r[\"ant\"] == \"ea28\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"last\")",
     "rawSql": "SELECT\r\n  \"time\",\r\n  \"ant\",\r\n  \"dts_state_ok\"\r\nFROM \"feng_stat\"\r\nWHERE \"dts_state_ok\" IS NOT NULL\r\n  AND $__timeFilter(\"time\")\r\nORDER BY \"time\" ASC"
    }
   ]
  },
  {
   "title": "All antenna dts state sync ok",
   "type": "stat",
   "description": "The reported sync state of DTS signals. Will report OK if all 12 lanes of a DTS link appear to be locked together.\nAs returned by:\nfeng.dts.get_status_dict()['state_ok']['sync_ok'].\nPolled every 60s.",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 45 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT\r\n  \"time\",\r\n  \"ant\",\r\n  \"dts_state_sync_ok\"\r\nFROM (\r\n  SELECT\r\n    \"time\",\r\n    \"ant\",\r\n    \"dts_state_sync_ok\",\r\n    ROW_NUMBER() OVER (PARTITION BY \"ant\" ORDER BY \"time\" DESC) AS rn\r\n  FROM \"feng_stat\"\r\n  WHERE \"dts_state_sync_ok\" IS NOT NULL\r\n    AND $__timeFilter(\"time\")\r\n)\r\nWHERE rn = 1\r\nORDER BY \"ant\" ASC"
    }
   ]
  },
  {
   "title": "All antenna DTS state lock ok",
   "type": "stat",
   "description": "The reported state of the DTS lock, which indicates correct recovery of the sync pattern embedded in DTS data streams.\nAs returned by:\nfeng.dts.get_status_dict()['state_ok']['lock_ok'].\nPolled every 60s.",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "iox",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"fengine\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"feng_stat\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"dts_state_lock_ok\")\r\n  |> filter(fn: (r) => r[\"ant\"] == \"ea01\" or r[\"ant\"] == \"ea02\" or r[\"ant\"] == \"ea03\" or r[\"ant\"] == \"ea04\" or r[\"ant\"] == \"ea05\" or r[\"ant\"] == \"ea06\" or r[\"ant\"] == \"ea07\" or r[\"ant\"] == \"ea08\" or r[\"ant\"] == \"ea09\" or r[\"ant\"] == \"ea10\" or r[\"ant\"] == \"ea11\" or r[\"ant\"] == \"ea12\" or r[\"ant\"] == \"ea13\" or r[\"ant\"] == \"ea14\" or r[\"ant\"] == \"ea15\" or r[\"ant\"] == \"ea17\" or r[\"ant\"] == \"ea16\" or r[\"ant\"] == \"ea18\" or r[\"ant\"] == \"ea19\" or r[\"ant\"] == \"ea20\" or r[\"ant\"] == \"ea21\" or r[\"ant\"] == \"ea22\" or r[\"ant\"] == \"ea23\" or r[\"ant\"] == \"ea24\" or r[\"ant\"] == \"ea25\" or r[\"ant\"] == \"ea26\" or r[\"ant\"] == \"ea27\" or r[\"ant\"] == \"ea28\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"last\")",
     "rawSql": "SELECT\r\n  \"time\",\r\n  \"ant\",\r\n  \"dts_state_lock_ok\"\r\nFROM (\r\n  SELECT\r\n    \"time\",\r\n    \"ant\",\r\n    \"dts_state_lock_ok\",\r\n    ROW_NUMBER() OVER (PARTITION BY \"ant\" ORDER BY \"time\" DESC) AS rn\r\n  FROM \"feng_stat\"\r\n  WHERE \"dts_state_lock_ok\" IS NOT NULL\r\n    AND $__timeFilter(\"time\")\r\n)\r\nWHERE rn = 1\r\nORDER BY \"ant\" ASC"
    }
   ]
  },
  {
   "title": "All antenna DTS FPGA Transceiver Lock",
   "type": "stat",
   "description": "Reported lock state of FPGA \"GTY\" transceivers, as returned by:\nfeng.dts.get_status_dict()['state_ok']['gty_lock_ok'].\nPolled every 60s.",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "iox",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"fengine\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"feng_stat\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"dts_state_gty_lock_ok\")\r\n  |> filter(fn: (r) => r[\"ant\"] == \"ea01\" or r[\"ant\"] == \"ea02\" or r[\"ant\"] == \"ea03\" or r[\"ant\"] == \"ea04\" or r[\"ant\"] == \"ea05\" or r[\"ant\"] == \"ea06\" or r[\"ant\"] == \"ea07\" or r[\"ant\"] == \"ea08\" or r[\"ant\"] == \"ea09\" or r[\"ant\"] == \"ea10\" or r[\"ant\"] == \"ea11\" or r[\"ant\"] == \"ea12\" or r[\"ant\"] == \"ea13\" or r[\"ant\"] == \"ea14\" or r[\"ant\"] == \"ea15\" or r[\"ant\"] == \"ea17\" or r[\"ant\"] == \"ea16\" or r[\"ant\"] == \"ea18\" or r[\"ant\"] == \"ea19\" or r[\"ant\"] == \"ea20\" or r[\"ant\"] == \"ea21\" or r[\"ant\"] == \"ea22\" or r[\"ant\"] == \"ea23\" or r[\"ant\"] == \"ea24\" or r[\"ant\"] == \"ea25\" or r[\"ant\"] == \"ea26\" or r[\"ant\"] == \"ea27\" or r[\"ant\"] == \"ea28\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"last\")",
     "rawSql": "SELECT\r\n  \"time\",\r\n  \"ant\",\r\n  \"dts_state_gty_lock_ok\"\r\nFROM (\r\n  SELECT\r\n    \"time\",\r\n    \"ant\",\r\n    \"dts_state_gty_lock_ok\",\r\n    ROW_NUMBER() OVER (PARTITION BY \"ant\" ORDER BY \"time\" DESC) AS rn\r\n  FROM \"feng_stat\"\r\n  WHERE \"dts_state_gty_lock_ok\" IS NOT NULL\r\n    AND $__timeFilter(\"time\")\r\n)\r\nWHERE rn = 1\r\nORDER BY \"ant\" ASC"
    }
   ]
  },
  {
   "title": "All antenna DTS Accumulated Parity Errors",
   "type": "timeseries",
   "description": "Number of detected parity errors since last DTS reset,  all DTS lanes and antenna",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dataset": "iox",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"fengine\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"feng_stat\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"acc\")\r\n  |> filter(fn: (r) => r[\"ant\"] == \"ea01\" or r[\"ant\"] == \"ea02\" or r[\"ant\"] == \"ea03\" or r[\"ant\"] == \"ea04\" or r[\"ant\"] == \"ea05\" or r[\"ant\"] == \"ea07\" or r[\"ant\"] == \"ea06\" or r[\"ant\"] == \"ea08\" or r[\"ant\"] == \"ea10\" or r[\"ant\"] == \"ea09\" or r[\"ant\"] == \"ea11\" or r[\"ant\"] == \"ea13\" or r[\"ant\"] == \"ea12\" or r[\"ant\"] == \"ea14\" or r[\"ant\"] == \"ea15\" or r[\"ant\"] == \"ea16\" or r[\"ant\"] == \"ea17\" or r[\"ant\"] == \"ea18\" or r[\"ant\"] == \"ea19\" or r[\"ant\"] == \"ea20\" or r[\"ant\"] == \"ea21\" or r[\"ant\"] == \"ea22\" or r[\"ant\"] == \"ea23\" or r[\"ant\"] == \"ea24\" or r[\"ant\"] == \"ea25\" or r[\"ant\"] == \"ea26\" or r[\"ant\"] == \"ea28\" or r[\"ant\"] == \"ea27\")\r\n  |> filter(fn: (r) => r[\"dts_lane\"] == \"0\" or r[\"dts_lane\"] == \"1\" or r[\"dts_lane\"] == \"10\" or r[\"dts_lane\"] == \"11\" or r[\"dts_lane\"] == \"2\" or r[\"dts_lane\"] == \"3\" or r[\"dts_lane\"] == \"4\" or r[\"dts_lane\"] == \"5\" or r[\"dts_lane\"] == \"6\" or r[\"dts_lane\"] == \"7\" or r[\"dts_lane\"] == \"8\" or r[\"dts_lane\"] == \"9\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")",
     "rawSql": "SELECT\r\n  \"time\",\r\n  \"ant\",\r\n  SUM(\"acc\") AS \"total_acc_errors\"\r\nFROM \"feng_stat\"\r\nWHERE \"acc\" IS NOT NULL\r\n  AND $__timeFilter(\"time\")\r\nGROUP BY \"time\", \"ant\"\r\nORDER BY \"time\" ASC"
    }
   ]
  },
  {
   "title": "All antenna DTS Parity Errors per second",
   "type": "timeseries",
   "description": "Number of detected parity errors per second for each DTS lane and each antenna",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dataset": "iox",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"fengine\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"feng_stat\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"count\")\r\n  |> filter(fn: (r) => r[\"ant\"] == \"ea01\" or r[\"ant\"] == \"ea02\" or r[\"ant\"] == \"ea03\" or r[\"ant\"] == \"ea04\" or r[\"ant\"] == \"ea05\" or r[\"ant\"] == \"ea07\" or r[\"ant\"] == \"ea06\" or r[\"ant\"] == \"ea08\" or r[\"ant\"] == \"ea10\" or r[\"ant\"] == \"ea09\" or r[\"ant\"] == \"ea11\" or r[\"ant\"] == \"ea13\" or r[\"ant\"] == \"ea12\" or r[\"ant\"] == \"ea14\" or r[\"ant\"] == \"ea15\" or r[\"ant\"] == \"ea16\" or r[\"ant\"] == \"ea17\" or r[\"ant\"] == \"ea18\" or r[\"ant\"] == \"ea19\" or r[\"ant\"] == \"ea20\" or r[\"ant\"] == \"ea21\" or r[\"ant\"] == \"ea22\" or r[\"ant\"] == \"ea23\" or r[\"ant\"] == \"ea24\" or r[\"ant\"] == \"ea25\" or r[\"ant\"] == \"ea26\" or r[\"ant\"] == \"ea28\" or r[\"ant\"] == \"ea27\")\r\n  |> filter(fn: (r) => r[\"dts_lane\"] == \"0\" or r[\"dts_lane\"] == \"1\" or r[\"dts_lane\"] == \"10\" or r[\"dts_lane\"] == \"11\" or r[\"dts_lane\"] == \"2\" or r[\"dts_lane\"] == \"3\" or r[\"dts_lane\"] == \"4\" or r[\"dts_lane\"] == \"5\" or r[\"dts_lane\"] == \"6\" or r[\"dts_lane\"] == \"7\" or r[\"dts_lane\"] == \"8\" or r[\"dts_lane\"] == \"9\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")",
     "rawSql": "SELECT\r\n  \"time\",\r\n  \"ant\",\r\n  SUM(\"count\") AS \"total_errors_per_second\"\r\nFROM \"feng_stat\"\r\nWHERE \"count\" IS NOT NULL\r\n  AND $__timeFilter(\"time\")\r\nGROUP BY \"time\", \"ant\"\r\nORDER BY \"time\" ASC"
    }
   ]
  },
  {
   "title": "Equalisation Coefficient state for ${Antenna}",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 85 }
  },
  {
   "title": "Equalisation coefficient mean across frequency",
   "type": "timeseries",
   "description": "Since a single equalisation coefficient is applied across all channels on the F-Engine every configuration, the mean plotted here is equal to the equalisation coefficient (compare with the eq identical panel to verify).",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dataset": "iox",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"fengine\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"feng_stat\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"eq_mean_coeff\")\r\n  |> filter(fn: (r) => r[\"ant\"] == \"${Antenna}\")\r\n  |> filter(fn: (r) => r[\"stream\"] == \"0\" or r[\"stream\"] == \"1\" or r[\"stream\"] == \"2\" or r[\"stream\"] == \"3\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")",
     "rawSql": "SELECT\r\n  \"time\",\r\n  \"ant\",\r\n  AVG(\"eq_mean_coeff\") AS \"avg_eq_mean_coeff\"\r\nFROM \"feng_stat\"\r\nWHERE \"eq_mean_coeff\" IS NOT NULL\r\n  AND $__timeFilter(\"time\")\r\nGROUP BY \"time\", \"ant\"\r\nORDER BY \"time\" ASC"
    }
   ]
  },
  {
   "title": "Equalisation coefficient identical across the band for ${Antenna}",
   "type": "stat",
   "description": "As we apply a single equalisation coefficient to the whole band, this panel checks that the coefficients are equal for all frequency channels.",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 86 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "iox",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"fengine\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"feng_stat\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"eq_identical_coeffs\")\r\n  |> filter(fn: (r) => r[\"ant\"] == \"ea01\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")",
     "rawSql": "SELECT\r\n  \"time\",\r\n  \"eq_identical_coeffs\"\r\nFROM \"feng_stat\"\r\nWHERE \"ant\" = '${Antenna}'\r\n  AND \"eq_identical_coeffs\" IS NOT NULL\r\n  AND $__timeFilter(\"time\")\r\nORDER BY \"time\" DESC\r\nLIMIT 1"
    }
   ]
  },
  {
   "title": "F-Engine input stats for ${Antenna}",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 94 }
  },
  {
   "title": "Input data mean for $Antenna",
   "type": "timeseries",
   "description": "Fetched from the cosmic_fengine.input block, this graph depicts the mean input value taken per stream.",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 95 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dataset": "iox",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"fengine\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"feng_stat\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"inpt_mean\")\r\n  |> filter(fn: (r) => r[\"ant\"] == \"${Antenna}\")\r\n  |> filter(fn: (r) => r[\"stream\"] == \"0\" or r[\"stream\"] == \"1\" or r[\"stream\"] == \"2\" or r[\"stream\"] == \"3\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")",
     "rawSql": "SELECT\r\n  \"time\",\r\n  \"stream\",\r\n  \"inpt_mean\"\r\nFROM \"feng_stat\"\r\nWHERE \"ant\" = '${Antenna}'\r\n  AND \"inpt_mean\" IS NOT NULL\r\n  AND $__timeFilter(\"time\")\r\nORDER BY \"time\" ASC"
    }
   ]
  },
  {
   "title": "Input data power for ${Antenna}",
   "type": "timeseries",
   "description": "Fetched from the cosmic_fengine.input block, this graph depicts the power input value taken per stream",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 106 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dataset": "iox",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"fengine\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"feng_stat\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"inpt_power\")\r\n  |> filter(fn: (r) => r[\"ant\"] == \"${Antenna}\")\r\n  |> filter(fn: (r) => r[\"stream\"] == \"0\" or r[\"stream\"] == \"1\" or r[\"stream\"] == \"2\" or r[\"stream\"] == \"3\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")",
     "rawSql": "SELECT\r\n  \"time\",\r\n  \"stream\",\r\n  \"inpt_power\"\r\nFROM \"feng_stat\"\r\nWHERE \"ant\" = '${Antenna}'\r\n  AND \"inpt_power\" IS NOT NULL\r\n  AND $__timeFilter(\"time\")\r\nORDER BY \"time\" ASC"
    }
   ]
  },
  {
   "title": "Input data rms for ${Antenna}",
   "type": "timeseries",
   "description": "Fetched from the cosmic_fengine.input block, this graph depicts the rms input value taken per stream",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 117 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dataset": "iox",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"fengine\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"feng_stat\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"inpt_rms\")\r\n  |> filter(fn: (r) => r[\"ant\"] == \"ea01\")\r\n  |> filter(fn: (r) => r[\"stream\"] == \"0\" or r[\"stream\"] == \"1\" or r[\"stream\"] == \"2\" or r[\"stream\"] == \"3\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")",
     "rawSql": "SELECT\r\n  \"time\",\r\n  \"stream\",\r\n  \"inpt_rms\"\r\nFROM \"feng_stat\"\r\nWHERE \"ant\" = '${Antenna}'\r\n  AND \"inpt_rms\" IS NOT NULL\r\n  AND $__timeFilter(\"time\")\r\nORDER BY \"time\" ASC"
    }
   ]
  }
 ]
}