{
 "title": "COSMIC-VLA-DISKS",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Disc utilisation for cosmic-storage-* nodes",
   "type": "stat",
   "description": "Drive percentage used of the Cosmic storage drives",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{mountpoint=~\"/srv/data.+\",fstype!=\"rootfs\",group=~\"cosmic-storage-.+\"} * 100) /   node_filesystem_size_bytes{mountpoint=~\"/srv/data.+\",fstype!=\"rootfs\",group=~\"cosmic-storage-.+\"})",
     "legendFormat": "{{group}} : {{mountpoint}}"
    }
   ]
  },
  {
   "title": "Netboot home directory storage",
   "type": "stat",
   "description": "Drive percentage available of the net-booted home directory ",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{mountpoint=\"/\",fstype!=\"rootfs\",group=\"cosmic-head\"} * 100) /   node_filesystem_size_bytes{mountpoint=\"/\",fstype!=\"rootfs\",group=\"cosmic-head\"})"
    }
   ]
  },
  {
   "title": "Disc utilisation for cosmic-gpu-* nodes",
   "type": "stat",
   "description": "Percentage available for discs.",
   "gridPos": { "h": 23, "w": 24, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{mountpoint=~\"/mnt/buf.+\",group=~\"cosmic-gpu-.+\"} * 100) /   node_filesystem_size_bytes{mountpoint=~\"/mnt/buf.+\",group=~\"cosmic-gpu-.+\"})",
     "legendFormat": "{{group}} : {{mountpoint}}"
    }
   ]
  }
 ]
}