{
 "title": "COSMIC-VLA-GPU",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "node",
    "label": "COSMIC GPU node",
    "query": "cosmic-gpu-3, cosmic-gpu-4, cosmic-gpu-5, cosmic-gpu-6, cosmic-gpu-7, cosmic-gpu-8, cosmic-gpu-9, cosmic-gpu-10, cosmic-gpu-11, cosmic-gpu-12, cosmic-gpu-13, cosmic-gpu-14, cosmic-gpu-15, cosmic-gpu-16, cosmic-gpu-17, cosmic-gpu-18, cosmic-gpu-19, cosmic-gpu-20, cosmic-gpu-21, cosmic-gpu-22, cosmic-gpu-23"
   }
  ]
 },
 "panels": [
  {
   "title": "GPU Information",
   "type": "stat",
   "description": "Display the GPU names and models",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nvidia_smi_gpu_info{group=\"$node\"}",
     "legendFormat": "Model: {{name}}, UUID: {{uuid}}, Driver Version: {{driver_version}}, VBIOS: {{vbios_version}}"
    }
   ]
  },
  {
   "title": "Temperature (Celsius)",
   "type": "timeseries",
   "description": "Core GPU temperature. in degrees C.",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "nvidia_smi_temperature_gpu{group=\"$node\"}",
     "legendFormat": "{{uuid}}"
    }
   ]
  },
  {
   "title": "Power Draw",
   "type": "timeseries",
   "description": "The last measured power draw for the entire board, in watts. Only available if power management is supported. This reading is accurate to within +/- 5 watts.",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "nvidia_smi_power_draw_watts{group=\"$node\"}",
     "legendFormat": "{{uuid}}"
    }
   ]
  },
  {
   "title": "GPU Utilization %",
   "type": "timeseries",
   "description": "Percent of time over the past sample period during which one or more kernels was executing on the GPU.\\nThe sample period may be between 1 second and 1/6 second depending on the product.",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "nvidia_smi_utilization_gpu_ratio{group=\"$node\"}",
     "legendFormat": "{{uuid}}"
    }
   ]
  },
  {
   "title": "Memory Utilization %",
   "type": "timeseries",
   "description": "Percent of time over the past sample period during which global (device) memory was being read or written.\\nThe sample period may be between 1 second and 1/6 second depending on the product.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "nvidia_smi_utilization_memory_ratio{group=\"$node\"}",
     "legendFormat": "{{uuid}}"
    }
   ]
  },
  {
   "title": "Fan Speed %",
   "type": "timeseries",
   "description": "The fan speed value is the percent of the product's maximum noise tolerance fan speed that the device's fan is currently intended to run at. This value may exceed 100% in certain cases. Note: The reported speed is the intended fan speed. If the fan is physically blocked and unable to spin, this output will not match the actual fan speed. Many parts do not report fan speeds because they rely on cooling via fans in the surrounding enclosure.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "nvidia_smi_fan_speed_ratio{group=\"$node\"}",
     "legendFormat": "{{uuid}}"
    }
   ]
  },
  {
   "title": "Graphics Clock Speed",
   "type": "timeseries",
   "description": "Current frequency of graphics (shader) clock.",
   "gridPos": { "h": 13, "w": 6, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "rothz" } },
   "targets": [
    {
     "expr": "nvidia_smi_clocks_current_graphics_clock_hz{group=\"$node\"}",
     "legendFormat": "{{uuid}}"
    }
   ]
  },
  {
   "title": "Video Clock Speed",
   "type": "timeseries",
   "description": "Current frequency of video encoder/decoder clock.",
   "gridPos": { "h": 13, "w": 6, "x": 6, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "rothz" } },
   "targets": [
    {
     "expr": "nvidia_smi_clocks_current_video_clock_hz{group=\"$node\"}",
     "legendFormat": "{{uuid}}"
    }
   ]
  },
  {
   "title": "SM Clock Speed",
   "type": "timeseries",
   "description": "Current frequency of SM (Streaming Multiprocessor) clock.",
   "gridPos": { "h": 13, "w": 6, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "rothz" } },
   "targets": [
    {
     "expr": "nvidia_smi_clocks_current_sm_clock_hz{group=\"$node\"}",
     "legendFormat": "{{uuid}}"
    }
   ]
  },
  {
   "title": "Memory Clock Speed",
   "type": "timeseries",
   "description": "Current frequency of memory clock.",
   "gridPos": { "h": 13, "w": 6, "x": 18, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "rothz" } },
   "targets": [
    {
     "expr": "nvidia_smi_clocks_current_memory_clock_hz{group=\"$node\"}",
     "legendFormat": "{{uuid}}"
    }
   ]
  }
 ]
}